[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/zebflow/geonative"
homepage = "https://geonative.zebflow.com"
authors = ["Zebflow <hello@zebflow.com>"]
rust-version = "1.74"
categories = ["science::geo"]
keywords = ["geospatial", "gis", "geo"]
